name       : kpty
version    : 5.78.0
release    : 45
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.78/kpty-5.78.0.tar.xz : c3d1d6d431de7608f9e764ab40c4e1f0c1765d0f6f44c092c4d62e942e9511da
homepage   : https://community.kde.org/Frameworks
license    :
    - BSd-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming.library
summary    : Interfacing with pseudo terminal devices
description: |
    This library provides primitives to interface with pseudo terminal devices as well as a KProcess derived class for running child processes and communicating with them using a pty.
optimize   : lto
builddeps  :
    - kcoreaddons-devel
    - ki18n-devel
    - libutempter-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
