name       : kpty
version    : 5.28.0
release    : 1
source     :
    - http://download.kde.org/stable/frameworks/5.28/kpty-5.28.0.tar.xz : 161e662bdf05d07f506c4ed2e9a89818f7b0988eb192d74d91abde5efae742e0
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming
summary    : Interfacing with pseudo terminal devices
description: |
    This library provides primitives to interface with pseudo terminal devices as well as a KProcess derived class for running child processes and communicating with them using a pty.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - libutempter-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
