name       : kpty
version    : 5.107.0
release    : 68
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.107/kpty-5.107.0.tar.xz : 907ec5f4108d42fcfc7013c38e97c71ced2002dc14d311b589170e89ae4813f8
homepage   : https://community.kde.org/Frameworks
license    :
    - BSd-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming.library
summary    : Interfacing with pseudo terminal devices
description: |
    This library provides primitives to interface with pseudo terminal devices as well as a KProcess derived class for running child processes and communicating with them using a pty.
optimize   : lto
builddeps  :
    - kcoreaddons-devel
    - ki18n-devel
    - libutempter-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
