name       : kpty
version    : 5.106.0
release    : 67
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.106/kpty-5.106.0.tar.xz : 8c1a6db28c10a3605a0759b7ebb0363223653dc1ecf7d2f89e8fc4fa662d2ff2
homepage   : https://community.kde.org/Frameworks
license    :
    - BSd-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming.library
summary    : Interfacing with pseudo terminal devices
description: |
    This library provides primitives to interface with pseudo terminal devices as well as a KProcess derived class for running child processes and communicating with them using a pty.
optimize   : lto
builddeps  :
    - kcoreaddons-devel
    - ki18n-devel
    - libutempter-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
