name       : kpty
version    : 5.88.0
release    : 54
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.88/kpty-5.88.0.tar.xz : ca2a37fbe0c54ba9e7ff0e7e7c20d86621735ce85f093f79929d51e191d4c061
homepage   : https://community.kde.org/Frameworks
license    :
    - BSd-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming.library
summary    : Interfacing with pseudo terminal devices
description: |
    This library provides primitives to interface with pseudo terminal devices as well as a KProcess derived class for running child processes and communicating with them using a pty.
optimize   : lto
builddeps  :
    - kcoreaddons-devel
    - ki18n-devel
    - libutempter-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
