name       : kpty
version    : 5.77.0
release    : 43
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.77/kpty-5.77.0.tar.xz : 904bf61cda153f092fc5e2d089a00d73152c2dca6f7a0035f3978d9a7322f1e1
homepage   : https://community.kde.org/Frameworks
license    :
    - BSd-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming.library
optimize   : lto
summary    : Interfacing with pseudo terminal devices
description: |
    This library provides primitives to interface with pseudo terminal devices as well as a KProcess derived class for running child processes and communicating with them using a pty.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - libutempter-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
