name       : kpty
version    : 5.99.0
release    : 63
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.99/kpty-5.99.0.tar.xz : a08489301dba85a766e2e6acbd62bf7faedd3d68279e0b2b1637541bebd0e86d
homepage   : https://community.kde.org/Frameworks
license    :
    - BSd-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming.library
summary    : Interfacing with pseudo terminal devices
description: |
    This library provides primitives to interface with pseudo terminal devices as well as a KProcess derived class for running child processes and communicating with them using a pty.
optimize   : lto
builddeps  :
    - kcoreaddons-devel
    - ki18n-devel
    - libutempter-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
