name       : kpty
version    : 5.100.0
release    : 64
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.100/kpty-5.100.0.tar.xz : f208561be774b93c95e00e822d9644cebd1dfd2f5efd243ef01c9d47a738b440
homepage   : https://community.kde.org/Frameworks
license    :
    - BSd-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming.library
summary    : Interfacing with pseudo terminal devices
description: |
    This library provides primitives to interface with pseudo terminal devices as well as a KProcess derived class for running child processes and communicating with them using a pty.
optimize   : lto
builddeps  :
    - kcoreaddons-devel
    - ki18n-devel
    - libutempter-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
