name       : kpty
version    : 5.61.0
release    : 28
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.61/kpty-5.61.0.tar.xz : b91a88c00d3387927d1f6886a04e6e5bcc615ee1d0e72f647d51320ebf73471c
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Interfacing with pseudo terminal devices
description: |
    This library provides primitives to interface with pseudo terminal devices as well as a KProcess derived class for running child processes and communicating with them using a pty.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - libutempter-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
