name       : kpty
version    : 5.82.0
release    : 49
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.82/kpty-5.82.0.tar.xz : 4ce060c934f0bad89bf75187f3122e1926c029e6df9dec2ab307397979f0a75d
homepage   : https://community.kde.org/Frameworks
license    :
    - BSd-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming.library
summary    : Interfacing with pseudo terminal devices
description: |
    This library provides primitives to interface with pseudo terminal devices as well as a KProcess derived class for running child processes and communicating with them using a pty.
optimize   : lto
builddeps  :
    - kcoreaddons-devel
    - ki18n-devel
    - libutempter-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
