name       : kpty
version    : 5.58.0
release    : 25
source     :
    - https://download.kde.org/stable/frameworks/5.58/kpty-5.58.0.tar.xz : 808a9f159e3d34630ae16d13c3ed6310c07fc9a38737110190892dcc903d5017
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Interfacing with pseudo terminal devices
description: |
    This library provides primitives to interface with pseudo terminal devices as well as a KProcess derived class for running child processes and communicating with them using a pty.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - libutempter-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
